pulp_admin_username: admin
pulp_galaxy_permissions:
  - galaxy.add_namespace
  - galaxy.change_namespace
  - galaxy.upload_to_namespace
  - ansible.modify_ansible_repo_content
  - galaxy.view_user
  - galaxy.delete_user
  - galaxy.add_user
  - galaxy.change_user
  - galaxy.delete_synclist
  - galaxy.change_synclist
  - galaxy.view_synclist
  - galaxy.add_synclist
  - galaxy.view_group
  - galaxy.delete_group
  - galaxy.add_group
  - galaxy.change_group
  - ansible.change_collectionremote
  - ansible.view_collectionremote
